version: '3.8'
services:
  server:
    container_name: server
    build:
      context: ./server
      args:
        NODE_ENV: development
    command: yarn start:dev
    ports:
      - 3010:3010
    environment:
      - NODE_ENV=development
      - PORT=3010
    volumes:
      - ./server/src:/app/src