version: "3.8"
services:
  server:
    container_name: server
    build:
      context: ./server
      args:
        NODE_ENV: development
    command: yarn start:dev
    ports:
      - 3010:3010
    environment:
      - NODE_ENV=development
      - PORT=3010
    volumes:
      - ./server/src:/app/src
  db:
    container_name: db
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=root
      - POSTGRES_DB=concerts-app

volumes:
  db_data:
