import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { config } from "@fortawesome/fontawesome-svg-core";

import "@fortawesome/fontawesome-svg-core/styles.css";
import "react-toastify/dist/ReactToastify.css";

config.autoAddCss = false;

import "./globals.css";

import { SideBar } from "@/components";

import { App } from "./app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <App>
          <div className="grid grid-cols-8 h-screen md:grid-rows md:grid-cols-none md:h-full">
            <div className="border-2 col-span-1 md:border-0 md:col-span-7">
              <SideBar />
            </div>
            <div className="border-2 col-span-7 overflow-y-auto">
              {children}
            </div>
          </div>
        </App>
      </body>
    </html>
  );
}
