import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { SideBar } from "@/components";

import { App } from "./app";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <App>
          <div className="grid grid-flow-col grid-cols-8 h-screen">
            <div className="border-2">
              <SideBar />
            </div>
            <div className="border-2 col-span-7">{children}</div>
          </div>
        </App>
      </body>
    </html>
  );
}
